[platformio]
default_envs = esp32dev

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
upload_speed = 115200

lib_deps =
    bblanchon/ArduinoJson
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306
    adafruit/RTClib

[env:esp32dev]
board = esp32dev

upload_port = /dev/cu.usbserial-58B90171271
monitor_port = /dev/cu.usbserial-58B90171271

[env:esp32c3_supermini]
board = esp32-c3-devkitm-1

build_flags =
    -D BOARD_ESP32_C3_SUPER_MINI
