[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

upload_port = /dev/cu.usbserial-58B90171271
monitor_port = /dev/cu.usbserial-58B90171271

monitor_speed = 115200
upload_speed = 115200

lib_deps =
    bblanchon/ArduinoJson
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306